In [2]:
import pandas as pd

# Read in Datasets

- For the St. Louis it says Billions in 2017 USD. This means that all the values are inflation-adjusted to 2017 Dollar Value. (Read GDP)

In [13]:
gdp = pd.read_csv('Datasets/GDP_St_Louis_Federal.csv')
gdp['GDPC1'] = gdp['GDPC1'] * 1_000_000_000
gdp

    observation_date         GDPC1
0         1947-01-01  2.182681e+12
1         1947-04-01  2.176892e+12
2         1947-07-01  2.172432e+12
3         1947-10-01  2.206452e+12
4         1948-01-01  2.239682e+12
..               ...           ...
310       2024-07-01  2.347857e+13
311       2024-10-01  2.358654e+13
312       2025-01-01  2.354821e+13
313       2025-04-01  2.377098e+13
314       2025-07-01  2.402683e+13

[315 rows x 2 columns]

In [38]:
tourism_percent = pd.read_csv('Datasets/Tourism Percent Contribution to GDP.csv')

# melt() transforms wide data into long data
tourism_percent = tourism_percent.melt(id_vars='country_name',
                                       var_name='year',
                                       value_name='percent')
tourism_percent = tourism_percent[tourism_percent['year'] != 'Unnamed: 35']
tourism_percent['year'] = tourism_percent['year'].astype(int)
tourism_percent

     country_name  year  percent
0   United States  1995    7.780
1   United States  1996    8.185
2   United States  1997    8.303
3   United States  1998    8.422
4   United States  1999    8.460
5   United States  2000    8.943
6   United States  2001    8.521
7   United States  2002    8.187
8   United States  2003    8.082
9   United States  2004    8.271
10  United States  2005    8.124
11  United States  2006    8.144
12  United States  2007    8.204
13  United States  2008    8.288
14  United States  2009    7.647
15  United States  2010    7.439
16  United States  2011    7.792
17  United States  2012    7.848
18  United States  2013    7.791
19  United States  2014    7.821
20  United States  2015    7.686
21  United States  2016    7.766
22  United States  2017    7.743
23  United States  2018    7.780
24  United States  2019    7.851
25  United States  2020    7.910
26  United States  2021    7.963
27  United States  2022    8.010
28  United States  2023    8.066
29  United States  2024    8.123
30  United States  2025    8.185
31  United States  2026    8.248
32  United States  2027    8.312
33  United States  2028    8.368

In [26]:
usa_tourism = pd.read_csv('Datasets/USA Tourism.csv')
usa_tourism

,Country Name,Country Code,Series Name,Series Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,United States,USA,"International tourism, number of arrivals",ST.INT.ARVL,..,..,..,..,..,..,...,1.768645e+08,1.752615e+08,1.742918e+08,1.693249e+08,1.654780e+08,4.503700e+07,..,..,..,..
1,United States,USA,"International tourism, number of departures",ST.INT.DPRT,..,..,..,..,..,..,...,1.303640e+08,1.415260e+08,1.480450e+08,1.584454e+08,1.709301e+08,6.054990e+07,..,..,..,..
2,United States,USA,"International tourism, receipts (% of total ex...",ST.INT.RCPT.XP.ZS,..,..,..,..,..,..,...,1.010941e+01,1.019933e+01,9.762382e+00,9.509774e+00,9.375020e+00,3.875339e+00,..,..,..,..
3,United States,USA,"International tourism, receipts (current US$)",ST.INT.RCPT.CD,..,..,..,..,..,..,...,2.305740e+11,2.285490e+11,2.337580e+11,2.419840e+11,2.394470e+11,8.420500e+10,..,..,..,..
4,United States,USA,"International tourism, receipts for passenger ...",ST.INT.TRNR.CD,..,..,..,..,..,..,...,3.797200e+10,3.568300e+10,3.729000e+10,4.126200e+10,4.008200e+10,1.139300e+10,..,..,..,..
5,United States,USA,"International tourism, receipts for travel ite...",ST.INT.TVLR.CD,..,..,..,..,..,..,...,1.926020e+11,1.928660e+11,1.964680e+11,2.007220e+11,1.993650e+11,7.281200e+10,..,..,..,..
6,United States,USA,"International tourism, expenditures for passen...",ST.INT.TRNX.CD,..,..,..,..,..,..,...,4.200300e+10,3.848400e+10,4.035800e+10,5.067800e+10,5.279400e+10,1.303100e+10,..,..,..,..
7,United States,USA,"International tourism, expenditures for travel...",ST.INT.TVLX.CD,..,..,..,..,..,..,...,1.026660e+11,1.091560e+11,1.179290e+11,1.261400e+11,1.332850e+11,3.580600e+10,..,..,..,..
8,United States,USA,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,..,..,..,..,..,..,...,1.446690e+11,1.476400e+11,1.582870e+11,1.768180e+11,1.860790e+11,4.883700e+10,..,..,..,..
9,United States,USA,"International tourism, expenditures (% of tota...",ST.INT.XPND.MP.ZS,..,..,..,..,..,..,...,5.219770e+00,5.427372e+00,5.436778e+00,5.663472e+00,5.976775e+00,1.732494e+00,..,..,..,..
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Last Updated: 01/28/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Start Combining Data

In [45]:
gdp['year'] = pd.to_datetime(gdp['observation_date']).dt.year
annual_gdp = gdp.groupby('year')['GDPC1'].sum().reset_index()
annual_gdp = pd.merge(annual_gdp, tourism_percent, on='year', how='left')
annual_gdp = annual_gdp.drop(columns=['country_name'])
annual_gdp['tourism_contribution'] = round(annual_gdp['GDPC1'] * (annual_gdp['percent']/100), 3)
annual_gdp

    year         GDPC1  percent  tourism_contribution
0   1947  8.738457e+12      NaN                   NaN
1   1948  9.098506e+12      NaN                   NaN
2   1949  9.047711e+12      NaN                   NaN
3   1950  9.834127e+12      NaN                   NaN
4   1951  1.062528e+13      NaN                   NaN
..   ...           ...      ...                   ...
74  2021  8.612963e+13    7.963          6.858502e+12
75  2022  8.830372e+13    8.010          7.073128e+12
76  2023  9.089488e+13    8.066          7.331581e+12
77  2024  9.343374e+13    8.123          7.589623e+12
78  2025  7.134602e+13    8.185          5.839672e+12

[79 rows x 4 columns]

In [48]:
annual_gdp[annual_gdp['year'] == 2025]

    year         GDPC1  percent  tourism_contribution
78  2025  7.134602e+13    8.185          5.839672e+12